using AutoMapper;
using CabinetOs.Model.Auth.SignUp;
using CabinetOs.Model.Dtos.Cabinet.Commands;
using CabinetOs.Model.Dtos.Cabinet.Queries;
using CabinetOs.Model.Dtos.CanvasSettings.Commands;
using CabinetOs.Model.Dtos.CanvasSettings.Queries;
using CabinetOs.Model.Dtos.Company.Commands;
using CabinetOs.Model.Dtos.Company.Queries;
using CabinetOs.Model.Dtos.ComponentTemplate.Commands;
using CabinetOs.Model.Dtos.ComponentTemplate.Queries;
using CabinetOs.Model.Dtos.ComponentTemplatePin.Commands;
using CabinetOs.Model.Dtos.ComponentTemplatePin.Queries;
using CabinetOs.Model.Dtos.Connection.Commands;
using CabinetOs.Model.Dtos.Connection.Queries;
using CabinetOs.Model.Dtos.Device.Commands;
using CabinetOs.Model.Dtos.Device.Queries;
using CabinetOs.Model.Dtos.DeviceCommand.Commands;
using CabinetOs.Model.Dtos.DeviceCommand.Queries;
using CabinetOs.Model.Dtos.DeviceStatus.Queries;
using CabinetOs.Model.Dtos.DeviceType.Queries;
using CabinetOs.Model.Dtos.DiagramAnnotation.Commands;
using CabinetOs.Model.Dtos.DiagramAnnotation.Queries;
using CabinetOs.Model.Dtos.IoChannel.Commands;
using CabinetOs.Model.Dtos.IoChannel.Queries;
using CabinetOs.Model.Dtos.Permission.Queries;
using CabinetOs.Model.Dtos.Pin.Commands;
using CabinetOs.Model.Dtos.Pin.Queries;
using CabinetOs.Model.Dtos.Role.Commands;
using CabinetOs.Model.Dtos.Role.Queries;
using CabinetOs.Model.Dtos.RolePermission.Commands;
using CabinetOs.Model.Dtos.RolePermission.Queries;
using CabinetOs.Model.Dtos.User.Commands;
using CabinetOs.Model.Dtos.User.Queries;
using CabinetOs.Model.Entities;

namespace CabinetOs.Business.Mappings;

public class MappingProfiles : Profile
{
    public MappingProfiles()
    {
        CreateMap<Company, Company>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Company, CompanyDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<CompanyCreateDto, Company>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        CreateMap<CompanyUpdateDto, Company>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ReverseMap();

        CreateMap<Cabinet, Cabinet>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Cabinet, CabinetBaseDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.Latitude, opt => opt.MapFrom(src => src.Latitude)).ForMember(dest => dest.Longitude, opt => opt.MapFrom(src => src.Longitude)).ForMember(dest => dest.LocationDescription, opt => opt.MapFrom(src => src.LocationDescription)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Cabinet, CabinetDetailDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.CompanyName, opt => opt.MapFrom(src => src.Company != default ? src.Company.Name : default)).ForMember(dest => dest.Latitude, opt => opt.MapFrom(src => src.Latitude)).ForMember(dest => dest.Longitude, opt => opt.MapFrom(src => src.Longitude)).ForMember(dest => dest.LocationDescription, opt => opt.MapFrom(src => src.LocationDescription)).ForMember(dest => dest.GsmIp, opt => opt.MapFrom(src => src.GsmIp)).ForMember(dest => dest.NetworkIp, opt => opt.MapFrom(src => src.NetworkIp)).ForMember(dest => dest.DeviceStatusId, opt => opt.MapFrom(src => src.DeviceStatusId)).ForMember(dest => dest.DeviceStatusName, opt => opt.MapFrom(src => src.DeviceStatus != default ? src.DeviceStatus.Name : default)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<CabinetCreateDto, Cabinet>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.Latitude, opt => opt.MapFrom(src => src.Latitude)).ForMember(dest => dest.Longitude, opt => opt.MapFrom(src => src.Longitude)).ForMember(dest => dest.LocationDescription, opt => opt.MapFrom(src => src.LocationDescription)).ForMember(dest => dest.GsmIp, opt => opt.MapFrom(src => src.GsmIp)).ForMember(dest => dest.NetworkIp, opt => opt.MapFrom(src => src.NetworkIp)).ForMember(dest => dest.ScadaBaseUrl, opt => opt.MapFrom(src => src.ScadaBaseUrl)).ForMember(dest => dest.ScadaCommandTimeoutMs, opt => opt.MapFrom(src => src.ScadaCommandTimeoutMs)).ForMember(dest => dest.ScadaIsEnabled, opt => opt.MapFrom(src => src.ScadaIsEnabled)).ReverseMap();
        CreateMap<CabinetUpdateDto, Cabinet>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Latitude, opt => opt.MapFrom(src => src.Latitude)).ForMember(dest => dest.Longitude, opt => opt.MapFrom(src => src.Longitude)).ForMember(dest => dest.LocationDescription, opt => opt.MapFrom(src => src.LocationDescription)).ForMember(dest => dest.GsmIp, opt => opt.MapFrom(src => src.GsmIp)).ForMember(dest => dest.NetworkIp, opt => opt.MapFrom(src => src.NetworkIp)).ForMember(dest => dest.ScadaBaseUrl, opt => opt.MapFrom(src => src.ScadaBaseUrl)).ForMember(dest => dest.ScadaCommandTimeoutMs, opt => opt.MapFrom(src => src.ScadaCommandTimeoutMs)).ForMember(dest => dest.ScadaIsEnabled, opt => opt.MapFrom(src => src.ScadaIsEnabled)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ReverseMap();

        CreateMap<User, User>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));

        CreateMap<SignUpRequest, User>()
            .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
            .ForMember(dest => dest.UserName, opt => opt.MapFrom(src => src.UserName))
            .ForMember(dest => dest.FullName, opt => opt.MapFrom(src => src.FullName))
            .ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId))
            .ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber))
            .ReverseMap();

        CreateMap<User, UserBaseDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.FullName, opt => opt.MapFrom(src => src.FullName)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<User, UserDetailDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.CompanyName, opt => opt.MapFrom(src => src.Company != default ? src.Company.Name : default)).ForMember(dest => dest.FullName, opt => opt.MapFrom(src => src.FullName)).ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<UserCreateDto, User>().ForMember(dest => dest.UserName, opt => opt.MapFrom(src => src.UserName)).ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.FullName, opt => opt.MapFrom(src => src.FullName)).ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber)).ReverseMap();
        CreateMap<UserUpdateDto, User>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.FullName, opt => opt.MapFrom(src => src.FullName)).ForMember(dest => dest.PhoneNumber, opt => opt.MapFrom(src => src.PhoneNumber)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ReverseMap();

        CreateMap<Role, Role>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Role, RoleDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<RoleCreateDto, Role>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ReverseMap();
        CreateMap<RoleUpdateDto, Role>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ReverseMap();

        CreateMap<RolePermission, RolePermission>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<RolePermission, RolePermissionDto>().ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.RoleId)).ForMember(dest => dest.PermissionId, opt => opt.MapFrom(src => src.PermissionId)).ForMember(dest => dest.PermissionCode, opt => opt.MapFrom(src => src.Permission != default ? src.Permission.Code : default)).ForMember(dest => dest.PermissionDisplayName, opt => opt.MapFrom(src => src.Permission != default ? src.Permission.DisplayName : default)).ForMember(dest => dest.PermissionCategory, opt => opt.MapFrom(src => src.Permission != default ? src.Permission.Category : default)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<RolePermissionCreateDto, RolePermission>().ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.RoleId)).ForMember(dest => dest.PermissionId, opt => opt.MapFrom(src => src.PermissionId)).ReverseMap();

        CreateMap<Permission, Permission>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Permission, PermissionDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Code, opt => opt.MapFrom(src => src.Code)).ForMember(dest => dest.DisplayName, opt => opt.MapFrom(src => src.DisplayName)).ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Category)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));

        CreateMap<DeviceCommand, DeviceCommand>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<DeviceCommand, DeviceCommandDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.DeviceId, opt => opt.MapFrom(src => src.DeviceId)).ForMember(dest => dest.DeviceName, opt => opt.MapFrom(src => src.Device != default ? src.Device.Name : default)).ForMember(dest => dest.IoChannelId, opt => opt.MapFrom(src => src.IoChannelId)).ForMember(dest => dest.CommandType, opt => opt.MapFrom(src => src.CommandType)).ForMember(dest => dest.PayloadJson, opt => opt.MapFrom(src => src.PayloadJson)).ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status)).ForMember(dest => dest.RequestedByUserId, opt => opt.MapFrom(src => src.RequestedByUserId)).ForMember(dest => dest.UserFullName, opt => opt.MapFrom(src => src.RequesterUser != default ? src.RequesterUser.FullName : default)).ForMember(dest => dest.SentAt, opt => opt.MapFrom(src => src.SentAt)).ForMember(dest => dest.RespondedAt, opt => opt.MapFrom(src => src.RespondedAt)).ForMember(dest => dest.ResultMessage, opt => opt.MapFrom(src => src.ResultMessage)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.DeletedBy, opt => opt.MapFrom(src => src.DeletedBy)).ForMember(dest => dest.IsDeleted, opt => opt.MapFrom(src => src.IsDeleted)).ForMember(dest => dest.DeletedDateUtc, opt => opt.MapFrom(src => src.DeletedDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<DeviceCommandCreateDto, DeviceCommand>().ForMember(dest => dest.DeviceId, opt => opt.MapFrom(src => src.DeviceId)).ForMember(dest => dest.IoChannelId, opt => opt.MapFrom(src => src.IoChannelId)).ForMember(dest => dest.CommandType, opt => opt.MapFrom(src => src.CommandType)).ForMember(dest => dest.PayloadJson, opt => opt.MapFrom(src => src.PayloadJson)).ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status)).ForMember(dest => dest.RequestedByUserId, opt => opt.MapFrom(src => src.RequestedByUserId)).ForMember(dest => dest.SentAt, opt => opt.MapFrom(src => src.SentAt)).ForMember(dest => dest.RespondedAt, opt => opt.MapFrom(src => src.RespondedAt)).ForMember(dest => dest.ResultMessage, opt => opt.MapFrom(src => src.ResultMessage)).ReverseMap();
        CreateMap<DeviceCommandUpdateDto, DeviceCommand>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.PayloadJson, opt => opt.MapFrom(src => src.PayloadJson)).ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status)).ForMember(dest => dest.SentAt, opt => opt.MapFrom(src => src.SentAt)).ForMember(dest => dest.RespondedAt, opt => opt.MapFrom(src => src.RespondedAt)).ForMember(dest => dest.ResultMessage, opt => opt.MapFrom(src => src.ResultMessage)).ReverseMap();

        CreateMap<Connection, Connection>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Connection, ConnectionDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.SourcePinId, opt => opt.MapFrom(src => src.SourcePinId)).ForMember(dest => dest.TargetPinId, opt => opt.MapFrom(src => src.TargetPinId)).ForMember(dest => dest.Label, opt => opt.MapFrom(src => src.Label)).ForMember(dest => dest.WireType, opt => opt.MapFrom(src => src.WireType)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.LineStyle, opt => opt.MapFrom(src => src.LineStyle)).ForMember(dest => dest.StrokeWidth, opt => opt.MapFrom(src => src.StrokeWidth)).ForMember(dest => dest.WaypointsJson, opt => opt.MapFrom(src => src.WaypointsJson)).ForMember(dest => dest.ZIndex, opt => opt.MapFrom(src => src.ZIndex)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.DeletedBy, opt => opt.MapFrom(src => src.DeletedBy)).ForMember(dest => dest.IsDeleted, opt => opt.MapFrom(src => src.IsDeleted)).ForMember(dest => dest.DeletedDateUtc, opt => opt.MapFrom(src => src.DeletedDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<ConnectionCreateDto, Connection>().ForMember(dest => dest.SourcePinId, opt => opt.MapFrom(src => src.SourcePinId)).ForMember(dest => dest.TargetPinId, opt => opt.MapFrom(src => src.TargetPinId)).ForMember(dest => dest.Label, opt => opt.MapFrom(src => src.Label)).ForMember(dest => dest.WireType, opt => opt.MapFrom(src => src.WireType)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.LineStyle, opt => opt.MapFrom(src => src.LineStyle)).ForMember(dest => dest.StrokeWidth, opt => opt.MapFrom(src => src.StrokeWidth)).ForMember(dest => dest.WaypointsJson, opt => opt.MapFrom(src => src.WaypointsJson)).ForMember(dest => dest.ZIndex, opt => opt.MapFrom(src => src.ZIndex)).ReverseMap();
        CreateMap<ConnectionUpdateDto, Connection>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.SourcePinId, opt => opt.MapFrom(src => src.SourcePinId)).ForMember(dest => dest.TargetPinId, opt => opt.MapFrom(src => src.TargetPinId)).ForMember(dest => dest.Label, opt => opt.MapFrom(src => src.Label)).ForMember(dest => dest.WireType, opt => opt.MapFrom(src => src.WireType)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.LineStyle, opt => opt.MapFrom(src => src.LineStyle)).ForMember(dest => dest.StrokeWidth, opt => opt.MapFrom(src => src.StrokeWidth)).ForMember(dest => dest.WaypointsJson, opt => opt.MapFrom(src => src.WaypointsJson)).ForMember(dest => dest.ZIndex, opt => opt.MapFrom(src => src.ZIndex)).ReverseMap();

        CreateMap<IoChannel, IoChannel>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<IoChannel, IoChannelDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.DeviceId, opt => opt.MapFrom(src => src.DeviceId)).ForMember(dest => dest.ChannelNumber, opt => opt.MapFrom(src => src.ChannelNumber)).ForMember(dest => dest.Direction, opt => opt.MapFrom(src => src.Direction)).ForMember(dest => dest.IsEnabled, opt => opt.MapFrom(src => src.IsEnabled)).ForMember(dest => dest.CurrentValue, opt => opt.MapFrom(src => src.CurrentValue)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.ValueUpdatedAt, opt => opt.MapFrom(src => src.ValueUpdatedAt)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.DeletedBy, opt => opt.MapFrom(src => src.DeletedBy)).ForMember(dest => dest.IsDeleted, opt => opt.MapFrom(src => src.IsDeleted)).ForMember(dest => dest.DeletedDateUtc, opt => opt.MapFrom(src => src.DeletedDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<IoChannelCreateDto, IoChannel>().ForMember(dest => dest.DeviceId, opt => opt.MapFrom(src => src.DeviceId)).ForMember(dest => dest.ChannelNumber, opt => opt.MapFrom(src => src.ChannelNumber)).ForMember(dest => dest.Direction, opt => opt.MapFrom(src => src.Direction)).ForMember(dest => dest.IsEnabled, opt => opt.MapFrom(src => src.IsEnabled)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ReverseMap();
        CreateMap<IoChannelUpdateDto, IoChannel>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.ChannelNumber, opt => opt.MapFrom(src => src.ChannelNumber)).ForMember(dest => dest.Direction, opt => opt.MapFrom(src => src.Direction)).ForMember(dest => dest.IsEnabled, opt => opt.MapFrom(src => src.IsEnabled)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ReverseMap();

        CreateMap<Pin, Pin>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Pin, PinDetailDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.RelativeX, opt => opt.MapFrom(src => src.RelativeX)).ForMember(dest => dest.RelativeY, opt => opt.MapFrom(src => src.RelativeY)).ForMember(dest => dest.IoChannelId, opt => opt.MapFrom(src => src.IoChannelId)).ForMember(dest => dest.IoChannelName, opt => opt.MapFrom(src => src.IoChannel != default ? src.IoChannel.Name : default)).ForMember(dest => dest.Function, opt => opt.MapFrom(src => src.Function)).ForMember(dest => dest.SignalLayer, opt => opt.MapFrom(src => src.SignalLayer)).ForMember(dest => dest.VoltageLevel, opt => opt.MapFrom(src => src.VoltageLevel)).ForMember(dest => dest.DeviceId, opt => opt.MapFrom(src => src.DeviceId)).ForMember(dest => dest.DeviceName, opt => opt.MapFrom(src => src.Device != default ? src.Device.Name : default)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.DeletedBy, opt => opt.MapFrom(src => src.DeletedBy)).ForMember(dest => dest.IsDeleted, opt => opt.MapFrom(src => src.IsDeleted)).ForMember(dest => dest.DeletedDateUtc, opt => opt.MapFrom(src => src.DeletedDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Pin, PinDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.RelativeX, opt => opt.MapFrom(src => src.RelativeX)).ForMember(dest => dest.RelativeY, opt => opt.MapFrom(src => src.RelativeY)).ForMember(dest => dest.Function, opt => opt.MapFrom(src => src.Function)).ForMember(dest => dest.SignalLayer, opt => opt.MapFrom(src => src.SignalLayer)).ForMember(dest => dest.VoltageLevel, opt => opt.MapFrom(src => src.VoltageLevel)).ForMember(dest => dest.DeviceId, opt => opt.MapFrom(src => src.DeviceId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<PinCreateDto, Pin>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.RelativeX, opt => opt.MapFrom(src => src.RelativeX)).ForMember(dest => dest.RelativeY, opt => opt.MapFrom(src => src.RelativeY)).ForMember(dest => dest.IoChannelId, opt => opt.MapFrom(src => src.IoChannelId)).ForMember(dest => dest.Function, opt => opt.MapFrom(src => src.Function)).ForMember(dest => dest.SignalLayer, opt => opt.MapFrom(src => src.SignalLayer)).ForMember(dest => dest.VoltageLevel, opt => opt.MapFrom(src => src.VoltageLevel)).ForMember(dest => dest.DeviceId, opt => opt.MapFrom(src => src.DeviceId)).ReverseMap();
        CreateMap<PinUpdateDto, Pin>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.RelativeX, opt => opt.MapFrom(src => src.RelativeX)).ForMember(dest => dest.RelativeY, opt => opt.MapFrom(src => src.RelativeY)).ForMember(dest => dest.Function, opt => opt.MapFrom(src => src.Function)).ForMember(dest => dest.SignalLayer, opt => opt.MapFrom(src => src.SignalLayer)).ForMember(dest => dest.VoltageLevel, opt => opt.MapFrom(src => src.VoltageLevel)).ReverseMap();

        CreateMap<CanvasSettings, CanvasSettings>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<CanvasSettings, CanvasSettingsDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.GridSize, opt => opt.MapFrom(src => src.GridSize)).ForMember(dest => dest.SnapToGrid, opt => opt.MapFrom(src => src.SnapToGrid)).ForMember(dest => dest.BackgroundVariant, opt => opt.MapFrom(src => src.BackgroundVariant)).ForMember(dest => dest.GridColor, opt => opt.MapFrom(src => src.GridColor)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.MinZoom, opt => opt.MapFrom(src => src.MinZoom)).ForMember(dest => dest.MaxZoom, opt => opt.MapFrom(src => src.MaxZoom)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<CanvasSettingsCreateDto, CanvasSettings>().ForMember(dest => dest.GridSize, opt => opt.MapFrom(src => src.GridSize)).ForMember(dest => dest.SnapToGrid, opt => opt.MapFrom(src => src.SnapToGrid)).ForMember(dest => dest.BackgroundVariant, opt => opt.MapFrom(src => src.BackgroundVariant)).ForMember(dest => dest.GridColor, opt => opt.MapFrom(src => src.GridColor)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.MinZoom, opt => opt.MapFrom(src => src.MinZoom)).ForMember(dest => dest.MaxZoom, opt => opt.MapFrom(src => src.MaxZoom)).ReverseMap();
        CreateMap<CanvasSettingsUpdateDto, CanvasSettings>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.GridSize, opt => opt.MapFrom(src => src.GridSize)).ForMember(dest => dest.SnapToGrid, opt => opt.MapFrom(src => src.SnapToGrid)).ForMember(dest => dest.BackgroundVariant, opt => opt.MapFrom(src => src.BackgroundVariant)).ForMember(dest => dest.GridColor, opt => opt.MapFrom(src => src.GridColor)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.MinZoom, opt => opt.MapFrom(src => src.MinZoom)).ForMember(dest => dest.MaxZoom, opt => opt.MapFrom(src => src.MaxZoom)).ReverseMap();

        CreateMap<ComponentTemplate, ComponentTemplate>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<ComponentTemplate, ComponentTemplateBaseDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.DeviceTypeId, opt => opt.MapFrom(src => src.DeviceTypeId)).ForMember(dest => dest.IsSystemTemplate, opt => opt.MapFrom(src => src.IsSystemTemplate)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.BackgroundImageUrl, opt => opt.MapFrom(src => src.BackgroundImageUrl)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<ComponentTemplate, ComponentTemplateDetailDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.DeviceTypeId, opt => opt.MapFrom(src => src.DeviceTypeId)).ForMember(dest => dest.IsSystemTemplate, opt => opt.MapFrom(src => src.IsSystemTemplate)).ForMember(dest => dest.Width, opt => opt.MapFrom(src => src.Width)).ForMember(dest => dest.Height, opt => opt.MapFrom(src => src.Height)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.BackgroundImageUrl, opt => opt.MapFrom(src => src.BackgroundImageUrl)).ForMember(dest => dest.DeviceTypeName, opt => opt.MapFrom(src => src.DeviceType != default ? src.DeviceType.Name : default)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<ComponentTemplateCreateDto, ComponentTemplate>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.DeviceTypeId, opt => opt.MapFrom(src => src.DeviceTypeId)).ForMember(dest => dest.Width, opt => opt.MapFrom(src => src.Width)).ForMember(dest => dest.Height, opt => opt.MapFrom(src => src.Height)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.BackgroundImageUrl, opt => opt.MapFrom(src => src.BackgroundImageUrl)).ReverseMap();
        CreateMap<ComponentTemplateUpdateDto, ComponentTemplate>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.DeviceTypeId, opt => opt.MapFrom(src => src.DeviceTypeId)).ForMember(dest => dest.Width, opt => opt.MapFrom(src => src.Width)).ForMember(dest => dest.Height, opt => opt.MapFrom(src => src.Height)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.BackgroundImageUrl, opt => opt.MapFrom(src => src.BackgroundImageUrl)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ReverseMap();

        CreateMap<ComponentTemplatePin, ComponentTemplatePin>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<ComponentTemplatePin, ComponentTemplatePinDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.ComponentTemplateId, opt => opt.MapFrom(src => src.ComponentTemplateId)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.RelativeX, opt => opt.MapFrom(src => src.RelativeX)).ForMember(dest => dest.RelativeY, opt => opt.MapFrom(src => src.RelativeY)).ForMember(dest => dest.ChannelNumber, opt => opt.MapFrom(src => src.ChannelNumber)).ForMember(dest => dest.Function, opt => opt.MapFrom(src => src.Function)).ForMember(dest => dest.Direction, opt => opt.MapFrom(src => src.Direction)).ForMember(dest => dest.SignalLayer, opt => opt.MapFrom(src => src.SignalLayer)).ForMember(dest => dest.VoltageLevel, opt => opt.MapFrom(src => src.VoltageLevel)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<ComponentTemplatePinCreateDto, ComponentTemplatePin>().ForMember(dest => dest.ComponentTemplateId, opt => opt.MapFrom(src => src.ComponentTemplateId)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.RelativeX, opt => opt.MapFrom(src => src.RelativeX)).ForMember(dest => dest.RelativeY, opt => opt.MapFrom(src => src.RelativeY)).ForMember(dest => dest.ChannelNumber, opt => opt.MapFrom(src => src.ChannelNumber)).ForMember(dest => dest.Function, opt => opt.MapFrom(src => src.Function)).ForMember(dest => dest.Direction, opt => opt.MapFrom(src => src.Direction)).ForMember(dest => dest.SignalLayer, opt => opt.MapFrom(src => src.SignalLayer)).ForMember(dest => dest.VoltageLevel, opt => opt.MapFrom(src => src.VoltageLevel)).ReverseMap();
        CreateMap<ComponentTemplatePinUpdateDto, ComponentTemplatePin>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.RelativeX, opt => opt.MapFrom(src => src.RelativeX)).ForMember(dest => dest.RelativeY, opt => opt.MapFrom(src => src.RelativeY)).ForMember(dest => dest.Function, opt => opt.MapFrom(src => src.Function)).ForMember(dest => dest.Direction, opt => opt.MapFrom(src => src.Direction)).ForMember(dest => dest.SignalLayer, opt => opt.MapFrom(src => src.SignalLayer)).ForMember(dest => dest.VoltageLevel, opt => opt.MapFrom(src => src.VoltageLevel)).ReverseMap();

        CreateMap<Device, Device>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Device, DeviceDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.IsLocked, opt => opt.MapFrom(src => src.IsLocked)).ForMember(dest => dest.CabinetId, opt => opt.MapFrom(src => src.CabinetId)).ForMember(dest => dest.DeviceStatusId, opt => opt.MapFrom(src => src.DeviceStatusId)).ForMember(dest => dest.ExternalCode, opt => opt.MapFrom(src => src.ExternalCode)).ForMember(dest => dest.LastSeen, opt => opt.MapFrom(src => src.LastSeen)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Device, DeviceDetailDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CoordinateX, opt => opt.MapFrom(src => src.CoordinateX)).ForMember(dest => dest.CoordinateY, opt => opt.MapFrom(src => src.CoordinateY)).ForMember(dest => dest.Rotation, opt => opt.MapFrom(src => src.Rotation)).ForMember(dest => dest.ZIndex, opt => opt.MapFrom(src => src.ZIndex)).ForMember(dest => dest.IsLocked, opt => opt.MapFrom(src => src.IsLocked)).ForMember(dest => dest.IsVisible, opt => opt.MapFrom(src => src.IsVisible)).ForMember(dest => dest.CabinetId, opt => opt.MapFrom(src => src.CabinetId)).ForMember(dest => dest.ComponentTemplateId, opt => opt.MapFrom(src => src.ComponentTemplateId)).ForMember(dest => dest.ComponentTemplateName, opt => opt.MapFrom(src => src.ComponentTemplate != default ? src.ComponentTemplate.Name : default)).ForMember(dest => dest.DeviceStatusId, opt => opt.MapFrom(src => src.DeviceStatusId)).ForMember(dest => dest.DeviceStatusName, opt => opt.MapFrom(src => src.DeviceStatus != default ? src.DeviceStatus.Name : default)).ForMember(dest => dest.IpAddress, opt => opt.MapFrom(src => src.IpAddress)).ForMember(dest => dest.MacAddress, opt => opt.MapFrom(src => src.MacAddress)).ForMember(dest => dest.ExternalCode, opt => opt.MapFrom(src => src.ExternalCode)).ForMember(dest => dest.LastSeen, opt => opt.MapFrom(src => src.LastSeen)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<DeviceCreateDto, Device>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CoordinateX, opt => opt.MapFrom(src => src.CoordinateX)).ForMember(dest => dest.CoordinateY, opt => opt.MapFrom(src => src.CoordinateY)).ForMember(dest => dest.Rotation, opt => opt.MapFrom(src => src.Rotation)).ForMember(dest => dest.ZIndex, opt => opt.MapFrom(src => src.ZIndex)).ForMember(dest => dest.IsLocked, opt => opt.MapFrom(src => src.IsLocked)).ForMember(dest => dest.IsVisible, opt => opt.MapFrom(src => src.IsVisible)).ForMember(dest => dest.CabinetId, opt => opt.MapFrom(src => src.CabinetId)).ForMember(dest => dest.ComponentTemplateId, opt => opt.MapFrom(src => src.ComponentTemplateId)).ForMember(dest => dest.IpAddress, opt => opt.MapFrom(src => src.IpAddress)).ForMember(dest => dest.MacAddress, opt => opt.MapFrom(src => src.MacAddress)).ForMember(dest => dest.ExternalCode, opt => opt.MapFrom(src => src.ExternalCode)).ReverseMap();
        CreateMap<DeviceUpdateDto, Device>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CoordinateX, opt => opt.MapFrom(src => src.CoordinateX)).ForMember(dest => dest.CoordinateY, opt => opt.MapFrom(src => src.CoordinateY)).ForMember(dest => dest.Rotation, opt => opt.MapFrom(src => src.Rotation)).ForMember(dest => dest.ZIndex, opt => opt.MapFrom(src => src.ZIndex)).ForMember(dest => dest.IsLocked, opt => opt.MapFrom(src => src.IsLocked)).ForMember(dest => dest.IsVisible, opt => opt.MapFrom(src => src.IsVisible)).ForMember(dest => dest.IpAddress, opt => opt.MapFrom(src => src.IpAddress)).ForMember(dest => dest.MacAddress, opt => opt.MapFrom(src => src.MacAddress)).ForMember(dest => dest.ExternalCode, opt => opt.MapFrom(src => src.ExternalCode)).ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive)).ReverseMap();

        CreateMap<DiagramAnnotation, DiagramAnnotation>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<DiagramAnnotation, DiagramAnnotationDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CoordinateX, opt => opt.MapFrom(src => src.CoordinateX)).ForMember(dest => dest.CoordinateY, opt => opt.MapFrom(src => src.CoordinateY)).ForMember(dest => dest.Width, opt => opt.MapFrom(src => src.Width)).ForMember(dest => dest.Height, opt => opt.MapFrom(src => src.Height)).ForMember(dest => dest.Rotation, opt => opt.MapFrom(src => src.Rotation)).ForMember(dest => dest.ZIndex, opt => opt.MapFrom(src => src.ZIndex)).ForMember(dest => dest.IsLocked, opt => opt.MapFrom(src => src.IsLocked)).ForMember(dest => dest.IsVisible, opt => opt.MapFrom(src => src.IsVisible)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.CabinetId, opt => opt.MapFrom(src => src.CabinetId)).ForMember(dest => dest.CabinetName, opt => opt.MapFrom(src => src.Cabinet != default ? src.Cabinet.Name : default)).ForMember(dest => dest.Text, opt => opt.MapFrom(src => src.Text)).ForMember(dest => dest.Shape, opt => opt.MapFrom(src => src.Shape)).ForMember(dest => dest.FontColor, opt => opt.MapFrom(src => src.FontColor)).ForMember(dest => dest.FontSize, opt => opt.MapFrom(src => src.FontSize)).ForMember(dest => dest.IsBold, opt => opt.MapFrom(src => src.IsBold)).ForMember(dest => dest.BorderColor, opt => opt.MapFrom(src => src.BorderColor)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<DiagramAnnotationCreateDto, DiagramAnnotation>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CoordinateX, opt => opt.MapFrom(src => src.CoordinateX)).ForMember(dest => dest.CoordinateY, opt => opt.MapFrom(src => src.CoordinateY)).ForMember(dest => dest.Width, opt => opt.MapFrom(src => src.Width)).ForMember(dest => dest.Height, opt => opt.MapFrom(src => src.Height)).ForMember(dest => dest.Rotation, opt => opt.MapFrom(src => src.Rotation)).ForMember(dest => dest.ZIndex, opt => opt.MapFrom(src => src.ZIndex)).ForMember(dest => dest.IsLocked, opt => opt.MapFrom(src => src.IsLocked)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.CabinetId, opt => opt.MapFrom(src => src.CabinetId)).ForMember(dest => dest.Text, opt => opt.MapFrom(src => src.Text)).ForMember(dest => dest.Shape, opt => opt.MapFrom(src => src.Shape)).ForMember(dest => dest.FontColor, opt => opt.MapFrom(src => src.FontColor)).ForMember(dest => dest.FontSize, opt => opt.MapFrom(src => src.FontSize)).ForMember(dest => dest.IsBold, opt => opt.MapFrom(src => src.IsBold)).ForMember(dest => dest.BorderColor, opt => opt.MapFrom(src => src.BorderColor)).ForMember(dest => dest.IsVisible, opt => opt.MapFrom(src => src.IsVisible)).ReverseMap();
        CreateMap<DiagramAnnotationUpdateDto, DiagramAnnotation>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.CoordinateX, opt => opt.MapFrom(src => src.CoordinateX)).ForMember(dest => dest.CoordinateY, opt => opt.MapFrom(src => src.CoordinateY)).ForMember(dest => dest.Width, opt => opt.MapFrom(src => src.Width)).ForMember(dest => dest.Height, opt => opt.MapFrom(src => src.Height)).ForMember(dest => dest.Rotation, opt => opt.MapFrom(src => src.Rotation)).ForMember(dest => dest.ZIndex, opt => opt.MapFrom(src => src.ZIndex)).ForMember(dest => dest.IsLocked, opt => opt.MapFrom(src => src.IsLocked)).ForMember(dest => dest.IsVisible, opt => opt.MapFrom(src => src.IsVisible)).ForMember(dest => dest.BackgroundColor, opt => opt.MapFrom(src => src.BackgroundColor)).ForMember(dest => dest.Text, opt => opt.MapFrom(src => src.Text)).ForMember(dest => dest.Shape, opt => opt.MapFrom(src => src.Shape)).ForMember(dest => dest.FontColor, opt => opt.MapFrom(src => src.FontColor)).ForMember(dest => dest.FontSize, opt => opt.MapFrom(src => src.FontSize)).ForMember(dest => dest.IsBold, opt => opt.MapFrom(src => src.IsBold)).ForMember(dest => dest.BorderColor, opt => opt.MapFrom(src => src.BorderColor)).ReverseMap();

        CreateMap<DeviceStatus, DeviceStatus>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<DeviceStatus, DeviceStatusDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.Icon, opt => opt.MapFrom(src => src.Icon)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<DeviceType, DeviceType>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<DeviceType, DeviceTypeDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Category)).ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy)).ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy)).ForMember(dest => dest.CreateDateUtc, opt => opt.MapFrom(src => src.CreateDateUtc)).ForMember(dest => dest.UpdateDateUtc, opt => opt.MapFrom(src => src.UpdateDateUtc)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
    }
}