// <auto-generated />
using System;
using CabinetOs.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CabinetOs.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CabinetOs.Model.Entities.Cabinet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeviceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("GsmIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetworkIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScadaBaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScadaCommandTimeoutMs")
                        .HasColumnType("int");

                    b.Property<bool>("ScadaIsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ScadaLastIngestAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeviceStatusId");

                    b.ToTable("Cabinet", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.CanvasSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BackgroundVariant")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GridColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GridSize")
                        .HasColumnType("int");

                    b.Property<double>("MaxZoom")
                        .HasColumnType("float");

                    b.Property<double>("MinZoom")
                        .HasColumnType("float");

                    b.Property<bool>("SnapToGrid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CanvasSettings", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a86b7a5-b6ed-436b-b4ce-13eec3a57a0b"),
                            Description = "",
                            IsActive = true,
                            Name = "System"
                        });
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.ComponentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BackgroundColor")
                        .HasColumnType("int");

                    b.Property<string>("BackgroundImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemTemplate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("ComponentTemplate", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.ComponentTemplatePin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ChannelNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ComponentTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("Function")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RelativeX")
                        .HasColumnType("float");

                    b.Property<double>("RelativeY")
                        .HasColumnType("float");

                    b.Property<int>("SignalLayer")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VoltageLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTemplateId");

                    b.ToTable("ComponentTemplatePin", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LineStyle")
                        .HasColumnType("int");

                    b.Property<Guid>("SourcePinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("StrokeWidth")
                        .HasColumnType("float");

                    b.Property<Guid>("TargetPinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaypointsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WireType")
                        .HasColumnType("int");

                    b.Property<int>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourcePinId");

                    b.HasIndex("TargetPinId");

                    b.ToTable("Connection", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComponentTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CoordinateX")
                        .HasColumnType("float");

                    b.Property<double>("CoordinateY")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeviceStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rotation")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("ComponentTemplateId");

                    b.HasIndex("DeviceStatusId");

                    b.ToTable("Device", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.DeviceCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommandType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IoChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IoChannelId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("DeviceCommand", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.DeviceStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Color = "#6B7280",
                            Description = "Cihaza ulasilamiyor.",
                            Icon = "wifi-off",
                            Name = "Offline"
                        },
                        new
                        {
                            Id = 1,
                            Color = "#22C55E",
                            Description = "Cihaz calisiyor ve haberlesiyor.",
                            Icon = "wifi",
                            Name = "Online"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#F59E0B",
                            Description = "Cihaz calisiyor ancak dikkat gerektiren bir durum var.",
                            Icon = "alert-triangle",
                            Name = "Warning"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#EF4444",
                            Description = "Kritik ariza; mudahale gerekiyor.",
                            Icon = "alert-octagon",
                            Name = "Critical"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#3B82F6",
                            Description = "Bakim modunda; alarmlari bastirilir.",
                            Icon = "wrench",
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Module",
                            Name = "ControlModule"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Module",
                            Name = "InputModule"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Module",
                            Name = "OutputModule"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Module",
                            Name = "LedModule"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Passive",
                            Name = "TerminalBlock"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Field",
                            Name = "Sensor"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Field",
                            Name = "Peripheral"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Power",
                            Name = "PowerSupply"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Measurement",
                            Name = "MeasurementDevice"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Field",
                            Name = "CardReader"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Power",
                            Name = "Mains"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Power",
                            Name = "CircuitBreaker"
                        });
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.DiagramAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CoordinateX")
                        .HasColumnType("float");

                    b.Property<double>("CoordinateY")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FontSize")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsBold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rotation")
                        .HasColumnType("float");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<int>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.ToTable("DiagramAnnotation", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.IoChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChannelNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValueUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("IoChannel", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Category = "Diagram",
                            Code = "ViewDiagram",
                            DisplayName = "Diyagrami goruntule"
                        },
                        new
                        {
                            Id = 1,
                            Category = "Diagram",
                            Code = "EditDiagram",
                            DisplayName = "Diyagrami duzenle"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Control",
                            Code = "ControlOutput",
                            DisplayName = "Cikis sur (role / kilit / siren)"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Alarm",
                            Code = "AcknowledgeAlarm",
                            DisplayName = "Alarm kabul et"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Admin",
                            Code = "ManageUsers",
                            DisplayName = "Kullanici yonet"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Admin",
                            Code = "ConfigureSystem",
                            DisplayName = "Sistem ayarlarini yapilandir"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Diagram",
                            Code = "ViewCamera",
                            DisplayName = "Kamera goruntule"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Data",
                            Code = "ExportData",
                            DisplayName = "Veri disari aktar"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Admin",
                            Code = "ManageWorkflow",
                            DisplayName = "Is akisi yonet"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Access",
                            Code = "ManageAccessCards",
                            DisplayName = "Gecis kartlarini yonet"
                        });
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Pin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Function")
                        .HasColumnType("int");

                    b.Property<Guid?>("IoChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RelativeX")
                        .HasColumnType("float");

                    b.Property<double>("RelativeY")
                        .HasColumnType("float");

                    b.Property<int>("SignalLayer")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VoltageLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IoChannelId");

                    b.ToTable("Pin", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("TTL")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmutable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b370875e-34cd-4b79-891c-93ae38f99d11"),
                            ConcurrencyStamp = "b370875e-34cd-4b79-891c-93ae38f99d11",
                            IsActive = true,
                            IsImmutable = true,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("cd6040ef-dacc-4678-9a85-154f12581cff"),
                            ConcurrencyStamp = "cd6040ef-dacc-4678-9a85-154f12581cff",
                            IsActive = true,
                            IsImmutable = true,
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            ConcurrencyStamp = "7138ec51-4f9e-4afd-b61b-5a9a4584f5da",
                            IsActive = true,
                            IsImmutable = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("1f20c152-530e-4064-a39c-bbbed341fe84"),
                            ConcurrencyStamp = "1f20c152-530e-4064-a39c-bbbed341fe84",
                            IsActive = true,
                            IsImmutable = true,
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        });
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 0
                        },
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da"),
                            PermissionId = 9
                        });
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2b8c14-6d5a-4e79-9c03-8a1f7be24d56"),
                            AccessFailedCount = 0,
                            CompanyId = new Guid("1a86b7a5-b6ed-436b-b4ce-13eec3a57a0b"),
                            ConcurrencyStamp = "3f2b8c14-6d5a-4e79-9c03-8a1f7be24d56",
                            Email = "admin@cabinetos.local",
                            EmailConfirmed = true,
                            FullName = "System Administrator",
                            IsActive = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@CABINETOS.LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPl0XbKqwLMRDvmoUpWzRIoURp+GWrBerfyKXrgX5OM9WFYLNUGb+GEKCmo6Fqfl/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5NDWQZ7JHFXK3MTPRV2Y6BCA4EGSU8LO",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("CabinetOs.Model.ProjectEntities.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Action")
                        .HasColumnType("tinyint");

                    b.Property<string>("ClientIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequesterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectArchives", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.ProjectEntities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Action")
                        .HasColumnType("tinyint");

                    b.Property<string>("ClientIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequesterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectLogs", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3f2b8c14-6d5a-4e79-9c03-8a1f7be24d56"),
                            RoleId = new Guid("7138ec51-4f9e-4afd-b61b-5a9a4584f5da")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Cabinet", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Company", "Company")
                        .WithMany("Cabinets")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CabinetOs.Model.Entities.DeviceStatus", "DeviceStatus")
                        .WithMany("Cabinets")
                        .HasForeignKey("DeviceStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("DeviceStatus");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.ComponentTemplate", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.DeviceType", "DeviceType")
                        .WithMany("ComponentTemplates")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.ComponentTemplatePin", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.ComponentTemplate", "ComponentTemplate")
                        .WithMany("ComponentTemplatePins")
                        .HasForeignKey("ComponentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentTemplate");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Connection", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Pin", "SourcePin")
                        .WithMany("SourcePinConnections")
                        .HasForeignKey("SourcePinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CabinetOs.Model.Entities.Pin", "TargetPin")
                        .WithMany("TargetPinConnections")
                        .HasForeignKey("TargetPinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourcePin");

                    b.Navigation("TargetPin");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Device", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Cabinet", "Cabinet")
                        .WithMany("Devices")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CabinetOs.Model.Entities.ComponentTemplate", "ComponentTemplate")
                        .WithMany("Devices")
                        .HasForeignKey("ComponentTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CabinetOs.Model.Entities.DeviceStatus", "DeviceStatus")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cabinet");

                    b.Navigation("ComponentTemplate");

                    b.Navigation("DeviceStatus");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.DeviceCommand", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Device", "Device")
                        .WithMany("DeviceCommands")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CabinetOs.Model.Entities.IoChannel", "IoChannel")
                        .WithMany("DeviceCommands")
                        .HasForeignKey("IoChannelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CabinetOs.Model.Entities.User", "RequesterUser")
                        .WithMany("DeviceCommands")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("IoChannel");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.DiagramAnnotation", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Cabinet", "Cabinet")
                        .WithMany("DiagramAnnotations")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.IoChannel", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Device", "Device")
                        .WithMany("IoChannels")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Pin", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Device", "Device")
                        .WithMany("Pins")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CabinetOs.Model.Entities.IoChannel", "IoChannel")
                        .WithMany("Pins")
                        .HasForeignKey("IoChannelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("IoChannel");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.RefreshToken", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.RolePermission", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CabinetOs.Model.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.User", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CabinetOs.Model.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CabinetOs.Model.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Cabinet", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("DiagramAnnotations");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Company", b =>
                {
                    b.Navigation("Cabinets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.ComponentTemplate", b =>
                {
                    b.Navigation("ComponentTemplatePins");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Device", b =>
                {
                    b.Navigation("DeviceCommands");

                    b.Navigation("IoChannels");

                    b.Navigation("Pins");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.DeviceStatus", b =>
                {
                    b.Navigation("Cabinets");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.DeviceType", b =>
                {
                    b.Navigation("ComponentTemplates");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.IoChannel", b =>
                {
                    b.Navigation("DeviceCommands");

                    b.Navigation("Pins");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Pin", b =>
                {
                    b.Navigation("SourcePinConnections");

                    b.Navigation("TargetPinConnections");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CabinetOs.Model.Entities.User", b =>
                {
                    b.Navigation("DeviceCommands");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
